CREATE TABLE BAN_BANCO(
    BCO_BANCO NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    BCO_NOMBRE VARCHAR2(100),
    BCO_PAIS VARCHAR2(30),
    CONSTRAINT BCO_BANCO PRIMARY KEY (BCO_BANCO)
);

CREATE TABLE BAN_DEPOSITO (
    DEP_DEPOSITO NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    DEP_BANCO NUMERIC,
    DEP_CUENTA NUMERIC,
    DEP_TIPO_CUENTA VARCHAR2(30),
    DEP_TIPO_DEPOSITO VARCHAR2(30),
    DEP_MONTO FLOAT,
    DEP_FECHA DATE,
    DEP_DESCRIPCION VARCHAR2(200),
    DEP_NUM_DEPOSITO VARCHAR2(30),
    CONSTRAINT DEP_DEPOSITO PRIMARY KEY (DEP_DEPOSITO),
    CONSTRAINT FK_BCO_BANCO_DEP_BANCO FOREIGN KEY (DEP_BANCO) REFERENCES BAN_BANCO (BCO_BANCO)
);

CREATE TABLE BAN_P_SERVICIO (
    PSV_P_SERVICIO NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PSV_PROVEEDOR_FACTURA NUMERIC,
    PSV_TIPO_SERVICIO VARCHAR2(30),
    PSV_NUM_DOCUMENTO VARCHAR2(30),
    PSV_MONEDA VARCHAR2(10),
    PSV_METODO_PAGO VARCHAR2(50),
    PSV_MONTO_TOTAL FLOAT,
    PSV_FECHA DATE,
    PSV_DESCRIPCION VARCHAR2(200),
    CONSTRAINT PSV_P_SERVICIO PRIMARY KEY (PSV_P_SERVICIO),
    CONSTRAINT FK_PFC_PROVEEDOR_FACTURA_PSV_PROVEEDOR_FACTURA FOREIGN KEY (PSV_PROVEEDOR_FACTURA) REFERENCES BAN_PROVEEDOR_FACTURA (PFC_PROVEEDOR_FACTURA)
);

CREATE TABLE BAN_PROVEEDOR_FACTURA (
    PFC_PROVEEDOR_FACTURA NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PFC_PROVEEDOR NUMERIC,
    PFC_FACTURA NUMERIC,
    CONSTRAINT PFC_PROVEEDOR_FACTURA PRIMARY KEY (PFC_PROVEEDOR_FACTURA),
    CONSTRAINT FK_PRO_PROVEEDOR_PFC_PROVEEDOR FOREIGN KEY (PFC_PROVEEDOR) REFERENCES BAN_PROVEEDOR (PRO_PROVEEDOR),
    CONSTRAINT FK_FAC_FACTURA_PFC_FACTURA FOREIGN KEY (PFC_FACTURA) REFERENCES BAN_FACTURA (FAC_FACTURA)
);
