DROP TABLE IF EXISTS BAN_DEPARTAMENTO;
DROP TABLE IF EXISTS BAN_LIBRO_AUX;
DROP TABLE IF EXISTS BAN_CONCILIACION;

-- Crear la tabla de Catálogo de Departamentos
CREATE TABLE BAN_DEPARTAMENTO (
    PK_DEP_DEPARTAMENTO NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    DEP_NOMBRE VARCHAR2(100),
    DEP_JEFE VARCHAR2(100),
    DEP_CORREO VARCHAR2(100),
    CONSTRAINT PK_BAN_DEPARTAMENTO PRIMARY KEY (PK_DEP_DEPARTAMENTO)
);

-- Crear la tabla de Libro Auxiliar
CREATE TABLE BAN_LIBRO_AUX (
    PK_LAX_LIBRO_AUX NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    FK_BCO_BANCO NUMERIC,
    FK_DEP_DEPARTAMENTO NUMERIC,
    LAX_FECHA DATE,
    LAX_MES VARCHAR2(30),
    LAX_FACTURA VARCHAR2(50),
    LAX_CONCEPTO VARCHAR2(255),
    LAX_DEBE NUMERIC,
    LAX_HABER NUMERIC,
    LAX_SALDO NUMERIC,
    CONSTRAINT PK_BAN_LIBRO_AUX PRIMARY KEY (PK_LAX_LIBRO_AUX),
    CONSTRAINT FK_BCO_BANCO_LIBRO_AUX FOREIGN KEY (FK_BCO_BANCO) REFERENCES BAN_BANCO(BCO_BANCO),
    CONSTRAINT FK_DEP_DEPARTAMENTO_LIBRO_AUX FOREIGN KEY (FK_DEP_DEPARTAMENTO) REFERENCES BAN_DEPARTAMENTO(PK_DEP_DEPARTAMENTO)
);

-- Crear la tabla de Conciliaciones bancarias
CREATE TABLE BAN_CONCILIACION (
    PK_CON_CONCILIACION NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    FK_BCO_BANCO NUMERIC,
    CON_MES VARCHAR2(30),
    FK_LAX_SALDO NUMERIC,
    FK_ESF_SALDO NUMERIC,
    CON_DIFERENCIA NUMERIC,
    CON_ESTADO VARCHAR2(30),
    CONSTRAINT PK_BAN_CONCILIACION PRIMARY KEY (PK_CON_CONCILIACION),
    CONSTRAINT FK_BCO_BANCO_CONCILIACION FOREIGN KEY (FK_BCO_BANCO) REFERENCES BAN_BANCO(BCO_BANCO),
    CONSTRAINT FK_LAX_SALDO_CONCILIACION FOREIGN KEY (FK_LAX_SALDO) REFERENCES BAN_LIBRO_AUX(LAX_LIBRO_AUX),
    CONSTRAINT FK_ESF_SALDO_CONCILIACION FOREIGN KEY (FK_ESF_SALDO) REFERENCES OTRA_TABLA_ESF_SALDO(FK_ESF_SALDO)
);
