/***TABLAS DE CHEQUES BANCARIOS***/

CREATE TABLE BAN_CHEQUE(
    CHQ_CHEQUE NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CTA_NUMERO NUMERIC,
    CHQ_FECHA DATE,
    CHQ_BENEFICIARIO VARCHAR2(255),
    CHQ_MONTO DECIMAL(15,2),
    CHQ_MOTIVO VARCHAR2(255),
    CHQ_NUM_CHEQUE VARCHAR2(30),
    CHQ_ESTADO VARCHAR2(50),
    CONSTRAINT PK_CHQ_CHEQUE PRIMARY KEY (CHQ_CHEQUE),
    CONSTRAINT FK_CTA_NUMERO FOREIGN KEY (CTA_NUMERO) REFERENCES BAN_CUENTA(CTA_CUENTA)
);

/***TABLA DE PAGOS DE NÓMINA***/

CREATE TABLE BAN_PAGO_NOMINA(
    PGN_PAGO_NOMINA NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CTA_NUMERO NUMERIC,
    EMP_EMPLEADO NUMERIC,     
    PGN_FECHA DATE,
    PGN_MONTO DECIMAL(15,2),
    PGN_CONCEPTO VARCHAR2(255),
    PGN_ESTADO_PAGO VARCHAR2(50),
    PGN_OBSERVACIONES VARCHAR2(500),
    CONSTRAINT PK_PGN_PAGO_NOMINA PRIMARY KEY (PGN_PAGO_NOMINA),
    CONSTRAINT FK_CTA_NUMERO_PGN FOREIGN KEY (CTA_NUMERO) REFERENCES BAN_CUENTA(CTA_CUENTA)
);

/***TABLA DE FACTURAS***/

CREATE TABLE BAN_FACTURA(
    FAC_FACTURA NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    FAC_FECHA DATE,
    FAC_CONCEPTO VARCHAR2(255),
    FAC_NOMBRE VARCHAR2(255),
    FAC_NIT VARCHAR2(20),
    FAC_TOTAL DECIMAL(15,2),
    FAC_CANTIDAD INTEGER,
    FAC_METODO_PAGO VARCHAR2(100),
    CONSTRAINT PK_FAC_FACTURA PRIMARY KEY (FAC_FACTURA)
);

