DROP TABLE IF EXISTS BAN_ESTADO_FINANCIERO;
DROP TABLE IF EXISTS BAN_ESTADO_C;
DROP TABLE IF EXISTS BAN_EMPLEADO;

CREATE TABLE BAN_ESTADO_C (
    ESC_ESTADO_C NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    BCO_BANCO NUMERIC,
    CTA_NUMERO NUMERIC,
    ESC_MES VARCHAR2(30),
    ESC_FECHA DATE,
    ESC_DOCUMENTO VARCHAR2(100),
    ESC_DESCRIPCION VARCHAR2(255),
    ESC_DEBITO NUMBER(18, 2),
    ESC_CREDITO NUMBER(18, 2),
    ESC_SALDO NUMBER(18, 2),
    CONSTRAINT PK_ESC_ESTADO_C PRIMARY KEY (ESC_ESTADO_C),
    CONSTRAINT FK_BCO_BANCO FOREIGN KEY (BCO_BANCO) REFERENCES BAN_BANCO (BCO_BANCO),
    CONSTRAINT FK_CTA_NUMERO FOREIGN KEY (CTA_NUMERO) REFERENCES BAN_CUENTA (CTA_CUENTA)
);



CREATE TABLE BAN_LIBRO_AUX (
    LAX_LIBRO_AUX NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    BCO_BANCO NUMERIC,
    DEP_DEPARTAMENTO NUMERIC,
    LAX_FECHA DATE,
    LAX_MES VARCHAR2(30),
    LAX_FACTURA VARCHAR2(100),
    LAX_CONCEPTO VARCHAR2(255),
    LAX_DEBE NUMBER(18, 2),
    LAX_HABER NUMBER(18, 2),
    LAX_SALDO NUMBER(18, 2),
    CONSTRAINT PK_BAN_LIBRO_AUX PRIMARY KEY (LAX_LIBRO_AUX),
    CONSTRAINT FK_BCO_BANCO_LIBRO_AUX FOREIGN KEY (BCO_BANCO) REFERENCES BAN_BANCO(BCO_BANCO),
    CONSTRAINT FK_DEP_DEPARTAMENTO_LIBRO_AUX FOREIGN KEY (DEP_DEPARTAMENTO) REFERENCES BAN_DEPARTAMENTO(DEP_DEPARTAMENTO)
);


CREATE TABLE BAN_ESTADO_FINANCIERO (
    ESF_ESTADO_FINANCIERO NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    LAX_LIBRO_AUX NUMERIC,
    ESC_ESTADO_C NUMERIC,
    ESF_TRANSACCION NUMERIC,
    ESF_TIPO_TRANSACCION VARCHAR2(50),
    ESF_FECHA DATE,
    ESF_SALDO NUMBER(18, 2),
    ESF_TIPO_SALDO VARCHAR2(50),
    ESF_NOMBRE_LIBRO VARCHAR2(100),
    ESF_BALANCE NUMBER(18, 2),
    CONSTRAINT PK_ESF_ESTADO_FINANCIERO PRIMARY KEY (ESF_ESTADO_FINANCIERO),
    CONSTRAINT FK_LAX_LIBRO_AUX FOREIGN KEY (LAX_LIBRO_AUX) REFERENCES BAN_LIBRO_AUX(LAX_LIBRO_AUX),
    CONSTRAINT FK_ESC_ESTADO_C FOREIGN KEY (ESC_ESTADO_C) REFERENCES BAN_ESTADO_C(ESC_ESTADO_C)
);


CREATE TABLE BAN_EMPLEADO (
    EMP_EMPLEADO NUMERIC GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    DEP_DEPARTAMENTO NUMERIC,
    EMP_NOMBRES VARCHAR2(100),
    EMP_APELLIDOS VARCHAR2(100),
    EMP_DPI VARCHAR2(20),
    EMP_FECHA_NAC DATE,
    EMP_PUESTO VARCHAR2(100),
    CONSTRAINT PK_EMP_EMPLEADO PRIMARY KEY (EMP_EMPLEADO),
    CONSTRAINT FK_DEP_DEPARTAMENTO FOREIGN KEY (DEP_DEPARTAMENTO) REFERENCES BAN_DEPARTAMENTO (DEP_DEPARTAMENTO)
);
