/***************BANCOS***************/
INSERT INTO BAN_BANCO (BCO_NOMBRE,BCO_PAIS) VALUES('BANCO INDUSTRIAL, S.A.', 'GUATEMALA');
INSERT INTO BAN_BANCO (BCO_NOMBRE,BCO_PAIS) VALUES('BANCO DE DESARROLLO RURAL, SOCIEDAD ANONIMA', 'GUATEMALA');
INSERT INTO BAN_BANCO (BCO_NOMBRE,BCO_PAIS) VALUES('BANCO AGROMERCANTIL DE GUATEMALA', 'GUATEMALA');
INSERT INTO BAN_BANCO (BCO_NOMBRE,BCO_PAIS) VALUES('BANK OF AMERICA, NOS ACCOUNT', 'ESTADOS UNIDOS');


/***************CUENTAS***************/

INSERT INTO BAN_CUENTA (CTA_NOMBRE,CTA_TIPO,CTA_BANCO, CTA_NUMERO, CTA_MONEDA)
    VALUES('EMPRESA LA GRATITUD SOCIEDAD ANONIMA', 'DM', 1, '4050019786','GTQ');

INSERT INTO BAN_CUENTA (CTA_NOMBRE,CTA_TIPO,CTA_BANCO, CTA_NUMERO, CTA_MONEDA)
    VALUES('EMPRESA LA GRATITUD SOCIEDAD ANONIMA', 'DM', 2, '3033001234','GTQ');

INSERT INTO BAN_CUENTA (CTA_NOMBRE,CTA_TIPO,CTA_BANCO, CTA_NUMERO, CTA_MONEDA)
    VALUES('EMPRESA LA GRATITUD SOCIEDAD ANONIMA', 'DM', 3, '0000654321','GTQ');

INSERT INTO BAN_CUENTA (CTA_NOMBRE,CTA_TIPO,CTA_BANCO, CTA_NUMERO, CTA_MONEDA)
    VALUES('EMPRESA LA GRATITUD SOCIEDAD ANONIMA', 'DM', 4, '004080047204','USD');


/***************TRANSFERENCIAS***************/

INSERT INTO BAN_TRANSFERENCIA 
(TRA_TIPO_CTA,
TRA_CTA_DEBITO,
TRA_CTA_CREDITO,
TRA_FECHA,
TRA_TIPO,
TRA_ESTATUS,
TRA_NUM_TRANSFERENCIA,
TRA_EMPLEADO_SOLICITA,
TRA_EMPLEADO_AUTORIZA,
TRA_MONTO,
TRA_COMENTARIO)
VALUES('DM',
'4080047204',
'004080047204',
'2023-03-14',
'INTERNACIONAL',
'RECIBIDA',
'COM 2300256243',
2,
1,
2718.82,
'06 TRANSF. USD - GTQ')


INSERT INTO BAN_TRANSFERENCIA 
(TRA_TIPO_CTA,
TRA_CTA_DEBITO,
TRA_CTA_CREDITO,
TRA_FECHA,
TRA_TIPO,
TRA_ESTATUS,
TRA_NUM_TRANSFERENCIA,
TRA_EMPLEADO_SOLICITA,
TRA_EMPLEADO_AUTORIZA,
TRA_MONTO,
TRA_COMENTARIO)
VALUES('DM',
'3033001234',
'GT68AMCN01010000000903721504',
'2023-03-14',
'ACH',
'ENVIADA',
'112015',
2,
1,
20000,
'INCOMING')
