INSERT INTO BAN_ESTADO_C (ESC_BANCO, ESC_CTA_NUMERO, ESC_MES, ESC_FECHA, ESC_DOCUMENTO, ESC_DESCRIPCION, ESC_DEBITO, ESC_CREDITO, ESC_SALDO)
VALUES (
    (SELECT BCO_BANCO FROM BAN_BANCO WHERE BCO_NOMBRE = 'BANCO INDUSTRIAL, S.A.' AND ROWNUM = 1),
    (SELECT CTA_CUENTA FROM BAN_CUENTA WHERE CTA_NOMBRE = 'EMPRESA LA GRATITUD SOCIEDAD ANONIMA' AND ROWNUM = 1),
    'Marzo 2024',
    TO_DATE('2024-03-14', 'YYYY-MM-DD'),
    'DOC-123456',
    'Pago de proveedores',
    1000.00,
    0.00,
    1000.00
);

INSERT INTO BAN_ESTADO_C (ESC_BANCO, ESC_CTA_NUMERO, ESC_MES, ESC_FECHA, ESC_DOCUMENTO, ESC_DESCRIPCION, ESC_DEBITO, ESC_CREDITO, ESC_SALDO)
VALUES (
    (SELECT BCO_BANCO FROM BAN_BANCO WHERE BCO_NOMBRE = 'BANCO DE DESARROLLO RURAL, SOCIEDAD ANONIMA' AND ROWNUM = 1),
    (SELECT CTA_CUENTA FROM BAN_CUENTA WHERE CTA_NOMBRE = 'EMPRESA LA GRATITUD SOCIEDAD ANONIMA' AND ROWNUM = 1),
    'Marzo 2024',
    TO_DATE('2024-03-15', 'YYYY-MM-DD'), 
    'DOC-789012',
    'Ingreso de ventas',
    0.00,
    1500.00, 
    1500.00 
);



INSERT INTO BAN_DEPARTAMENTO (DEP_NOMBRE, DEP_JEFE, DEP_CORREO)
VALUES ('Departamento de Finanzas', 'Juan Perez', 'juan.perez@gmail.com');

INSERT INTO BAN_DEPARTAMENTO (DEP_NOMBRE , DEP_JEFE, DEP_CORREO) VALUES
('Departamento de Logisitca', 'Jason Monroy', 'jasonm3@gmail.com');

INSERT INTO BAN_DEPARTAMENTO (DEP_NOMBRE, DEP_JEFE, DEP_CORREO) VALUES
('Departamento de Marketing/Ventas','Carlos Salgero','carlosSA@gmail.com');

INSERT INTO BAN_DEPARTAMENTO (DEP_NOMBRE, DEP_JEFE, DEP_CORREO) VALUES
('Departamento de Contabilidad','Byron Frederick','bfrederick@gmail.com');

INSERT INTO BAN_EMPLEADO (DEP_DEPARTAMENTO, EMP_NOMBRES, EMP_APELLIDOS, EMP_DPI, EMP_FECHA_NAC, EMP_PUESTO)
SELECT DEP_DEPARTAMENTO, 'Ana', 'Gonzalez', '1234567890123', TO_DATE('1995-10-20', 'YYYY-MM-DD'), 'Analista Financiero'
FROM BAN_DEPARTAMENTO
WHERE DEP_NOMBRE = 'Departamento de Finanzas'
AND ROWNUM = 1;

INSERT INTO BAN_EMPLEADO (DEP_DEPARTAMENTO, EMP_NOMBRES, EMP_APELLIDOS, EMP_DPI, EMP_FECHA_NAC, EMP_PUESTO)
SELECT DEP_DEPARTAMENTO, 'Pedro', 'Martinez', '9876543210987', TO_DATE('1990-08-15', 'YYYY-MM-DD'), 'Coordinador de Logistica'
FROM BAN_DEPARTAMENTO
WHERE DEP_NOMBRE = 'Departamento de Logisitca'
AND ROWNUM = 1;

INSERT INTO BAN_EMPLEADO (DEP_DEPARTAMENTO, EMP_NOMBRES, EMP_APELLIDOS, EMP_DPI, EMP_FECHA_NAC, EMP_PUESTO)
SELECT DEP_DEPARTAMENTO, 'Marta', 'Lopez', '4567890123456', TO_DATE('1988-12-10', 'YYYY-MM-DD'), 'Ejecutivo de Ventas'
FROM BAN_DEPARTAMENTO
WHERE DEP_NOMBRE = 'Departamento de Marketing/Ventas'
AND ROWNUM = 1;

INSERT INTO BAN_EMPLEADO (DEP_DEPARTAMENTO, EMP_NOMBRES, EMP_APELLIDOS, EMP_DPI, EMP_FECHA_NAC, EMP_PUESTO)
SELECT DEP_DEPARTAMENTO, 'Juan', 'Gomez', '7890123456789', TO_DATE('1992-04-25', 'YYYY-MM-DD'), 'Contador'
FROM BAN_DEPARTAMENTO
WHERE DEP_NOMBRE = 'Departamento de Contabilidad'
AND ROWNUM = 1;

INSERT INTO BAN_LIBRO_AUX (LAX_BANCO, LAX_DEPARTAMENTO, LAX_FECHA, LAX_MES, LAX_FACTURA, LAX_CONCEPTO, LAX_DEBE, LAX_HABER, LAX_SALDO)
SELECT BCO_BANCO, DEP_DEPARTAMENTO, TO_DATE('2024-03-14', 'YYYY-MM-DD'), 'Marzo 2024', 'FACT-001', 'Compra de activos', 2000.00, 0.00, 2000.00
FROM BAN_BANCO, BAN_DEPARTAMENTO
WHERE BCO_NOMBRE = 'BANCO INDUSTRIAL, S.A.'
AND DEP_NOMBRE = 'Departamento de Finanzas'
AND ROWNUM = 1;

INSERT INTO BAN_LIBRO_AUX (LAX_BANCO, LAX_DEPARTAMENTO, LAX_FECHA, LAX_MES, LAX_FACTURA, LAX_CONCEPTO, LAX_DEBE, LAX_HABER, LAX_SALDO)
SELECT BCO_BANCO, DEP_DEPARTAMENTO, TO_DATE('2024-03-15', 'YYYY-MM-DD'), 'Marzo 2024', 'FACT-002', 'Venta de productos', 0.00, 1500.00, 1500.00
FROM BAN_BANCO, BAN_DEPARTAMENTO
WHERE BCO_NOMBRE = 'BANCO DE DESARROLLO RURAL, SOCIEDAD ANONIMA'
AND DEP_NOMBRE = 'Departamento de Logisitca'
AND ROWNUM = 1;

INSERT INTO BAN_LIBRO_AUX (LAX_BANCO, LAX_DEPARTAMENTO, LAX_FECHA, LAX_MES, LAX_FACTURA, LAX_CONCEPTO, LAX_DEBE, LAX_HABER, LAX_SALDO)
SELECT BCO_BANCO, DEP_DEPARTAMENTO, TO_DATE('2024-03-15', 'YYYY-MM-DD'), 'Marzo 2024', 'FACT-003', 'Ingreso por ventas', 2500.00, 0.00, 2500.00
FROM BAN_BANCO, BAN_DEPARTAMENTO
WHERE BCO_NOMBRE = 'BANCO AGROMERCANTIL DE GUATEMALA'
AND DEP_NOMBRE = 'Departamento de Marketing/Ventas'
AND ROWNUM = 1;
